// All User Constants

export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS";
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL";

export const ROOMS_DETAILS_SUCCESS = "ROOMS_DETAILS_SUCCESS";
export const ROOMS_DETAILS_FAIL = "ROOMS_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
